conda-forge/xeus-feedstock

.ci_support/linux_cxx_compilergxx.yaml
recipe/meta.yaml

Release 0.15.0

---

recipe/meta.yaml

Release 0.17.0

---

recipe/meta.yaml

Release 0.18.1

---

recipe/meta.yaml

Release 0.19.1

---

recipe/meta.yaml

Update zeromq to 4.3.1

---

recipe/meta.yaml

Release 0.19.2

---

recipe/meta.yaml

rebuild 0.20.0 with conda-build 3.17.8

---

recipe/meta.yaml

Release 0.21.0

---

recipe/meta.yaml

Updated zeromq dependncy

---

recipe/meta.yaml

Release 0.22.0

---

recipe/meta.yaml

Release 0.23.1

---

recipe/meta.yaml

Release 0.23.6

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
recipe/meta.yaml

Release 0.23.7

---

recipe/build.sh
recipe/meta.yaml

Release 0238

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/win_.yaml
README.md
recipe/meta.yaml

Release 0.23.9

---

recipe/meta.yaml

Release 0.23.10

---

README.md
recipe/meta.yaml

Release 0.23.11

---

recipe/meta.yaml

Release 0.23.12

---

recipe/meta.yaml

Release 0.24.0

---

recipe/meta.yaml

Release 0.24.1

---

recipe/meta.yaml

Increased build number

---

recipe/meta.yaml

Release 0.24.3

---

recipe/meta.yaml

Release 0.24.4

---

recipe/meta.yaml

Release 0.25.0

---

recipe/meta.yaml

Release 0.25.1

---

recipe/meta.yaml

Release 0.25.3

---

recipe/meta.yaml

Release 1.0.1

---

recipe/meta.yaml

Upgraded build number for release 1.0.2

---

recipe/meta.yaml

Release 1.0.3

---

recipe/meta.yaml
recipe/patches/0001-Fixed-number-version-on-other-UNIX-like-platforms.patch

Fixed version number on UNIX-like platforms

---

recipe/meta.yaml

Release 2.3.1

---

recipe/meta.yaml

Release 2.4.0

---

recipe/meta.yaml

Release 3.0.2

---

recipe/meta.yaml

Release 3.0.4

---

recipe/meta.yaml

Release 3.0.5

---

recipe/meta.yaml

Release 3.1.1

---

recipe/meta.yaml

Release 3.1.2

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
README.md
recipe/meta.yaml

Release 3.1.4

---

recipe/meta.yaml

Release 3.2.0

---

recipe/meta.yaml

Release 4.0.1

---

.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.ci_support/win_64_.yaml
recipe/meta.yaml

Added stdlib dependency in build section

---

recipe/meta.yaml

Update xeus to 5.1.0

---

.ci_support/linux_64_.yaml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
recipe/meta.yaml

Release 5.1.1
